# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name  = "terragrunt"
    storage_account_name = "terragrunt2025test"
    container_name       = "tfstate"
    key                  = "terragrunt.tfstate"
    access_key           = "ahrMqc8UgDAx7wTEzS2bnpt6ZTnZenfngExPQeP3EB5d5VBScNk1+UxPZSJAQMnxlEzM7mR8Nnie+AStmpDVEw=="
  }
}
