# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.34.0"
    }
  }
}


provider "azurerm" {
  features {}
  subscription_id = "614cc79c-4ad7-4053-8860-ff970c4a1783"
}
