# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name  = "terragrunt"
    storage_account_name = "terragrunt2025thesis"
    container_name       = "tfstate"
    key                  = "terragrunt.tfstate"
    access_key           = "9R8pS/sebQqPvbo+32btT7eAhlkfJmF7827cAJ5Rl5CgvsBWo/FGSTezhKBZ8eYdfi1v3xQKWOum+AStM3fk5g=="
  }
}
